module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accent-100": "var(--accent-100)",
        "accent-50": "var(--accent-50)",
        "accent-500": "var(--accent-500)",
        "accent-950": "var(--accent-950)",
        basewhite: "var(--basewhite)",
        "cyan-50": "var(--cyan-50)",
        "cyan-700": "var(--cyan-700)",
        "error-50": "var(--error-50)",
        "error-500": "var(--error-500)",
        "error-700": "var(--error-700)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-900": "var(--gray-900)",
        graysblack: "var(--graysblack)",
        grayswhite: "var(--grayswhite)",
        "indigo-50": "var(--indigo-50)",
        "indigo-700": "var(--indigo-700)",
        "info-50": "var(--info-50)",
        "info-700": "var(--info-700)",
        "m-3syslighterror": "var(--m-3syslighterror)",
        "m-3syslightsurface": "var(--m-3syslightsurface)",
        "m3syslighton-surface": "var(--m3syslighton-surface)",
        "m3syslighton-surface-variant": "var(--m3syslighton-surface-variant)",
        "m3syslightoutline-variant": "var(--m3syslightoutline-variant)",
        "neutral-100": "var(--neutral-100)",
        "neutral-200": "var(--neutral-200)",
        "neutral-300": "var(--neutral-300)",
        "neutral-400": "var(--neutral-400)",
        "neutral-50": "var(--neutral-50)",
        "neutral-500": "var(--neutral-500)",
        "neutral-600": "var(--neutral-600)",
        "neutral-700": "var(--neutral-700)",
        "neutral-800": "var(--neutral-800)",
        "neutral-900": "var(--neutral-900)",
        "neutral-950": "var(--neutral-950)",
        "neutral500-base": "var(--neutral500-base)",
        neutralwhite: "var(--neutralwhite)",
        "on-surface-dark-low-emphasis": "var(--on-surface-dark-low-emphasis)",
        "primary-0": "var(--primary-0)",
        "primary-100": "var(--primary-100)",
        "primary-400": "var(--primary-400)",
        "primary-900": "var(--primary-900)",
        "secondarysecondary-base": "var(--secondarysecondary-base)",
        "secondery-200": "var(--secondery-200)",
        "secondery-300": "var(--secondery-300)",
        "secondery-400": "var(--secondery-400)",
        "secondery-500": "var(--secondery-500)",
        "secondery-800": "var(--secondery-800)",
        "secondery-950": "var(--secondery-950)",
        "success-50": "var(--success-50)",
        "success-600": "var(--success-600)",
        "success-700": "var(--success-700)",
        text: "var(--text)",
        "textprimary-black": "var(--textprimary-black)",
        "ui-base-200": "var(--ui-base-200)",
        "ui-base-300": "var(--ui-base-300)",
        "ui-base-50": "var(--ui-base-50)",
        "ui-base-ui-base-500": "var(--ui-base-ui-base-500)",
        "violet-50": "var(--violet-50)",
        "violet-600": "var(--violet-600)",
        "violet-700": "var(--violet-700)",
        white: "var(--white)",
        "yellow-50": "var(--yellow-50)",
        "yellow-700": "var(--yellow-700)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "14-regular": "var(--14-regular-font-family)",
        "body-base": "var(--body-base-font-family)",
        "body-bold-small": "var(--body-bold-small-font-family)",
        "body-emphasized": "var(--body-emphasized-font-family)",
        "body-medium": "var(--body-medium-font-family)",
        "body-regular": "var(--body-regular-font-family)",
        "body-regular-medium": "var(--body-regular-medium-font-family)",
        "body-semibold": "var(--body-semibold-font-family)",
        "caps-md": "var(--caps-md-font-family)",
        "display-large-semibold": "var(--display-large-semibold-font-family)",
        "display-medium-semibold": "var(--display-medium-semibold-font-family)",
        "display-small-semibold": "var(--display-small-semibold-font-family)",
        "headline-bold": "var(--headline-bold-font-family)",
        "headline-medium": "var(--headline-medium-font-family)",
        "headline-semibold": "var(--headline-semibold-font-family)",
        "label-medium": "var(--label-medium-font-family)",
        "label-regular": "var(--label-regular-font-family)",
        "label-small": "var(--label-small-font-family)",
        "m3-title-small": "var(--m3-title-small-font-family)",
        "single-line-body-base": "var(--single-line-body-base-font-family)",
        "text-sm-medium": "var(--text-sm-medium-font-family)",
        "text-sm-normal": "var(--text-sm-normal-font-family)",
        "text-xs-medium": "var(--text-xs-medium-font-family)",
        "title-medium": "var(--title-medium-font-family)",
        "title-regular": "var(--title-regular-font-family)",
        "title-semibold": "var(--title-semibold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "drop-shadow-100": "var(--drop-shadow-100)",
        shadow: "var(--shadow)",
        "shadow-black-lg": "var(--shadow-black-lg)",
        "shadow-black-sm": "var(--shadow-black-sm)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
