/**
 * DI tokens (Phase E3). Typed identifiers for injectable dependencies, kept in
 * one place so providers and consumers agree on identity and type.
 */

import { token } from './container';
import type { EventBus } from '../events/event-bus';
import type { ICustomerRepository } from '../../modules/customers/repositories/customer.repository';
import type { CustomerService } from '../../modules/customers/services/customer.service';
import type { IVehicleRepository } from '../../modules/vehicles/repositories/vehicle.repository';
import type { VehicleService } from '../../modules/vehicles/services/vehicle.service';
import type { IAppointmentRepository } from '../../modules/appointments/repositories/appointment.repository';
import type { AppointmentService } from '../../modules/appointments/services/appointment.service';
import type { IGarageRepository } from '../../modules/garage/repositories/garage.repository';
import type { GarageService } from '../../modules/garage/services/garage.service';
import type { IJobCardRepository } from '../../modules/jobcards/repositories/jobcard.repository';
import type { JobCardService } from '../../modules/jobcards/services/jobcard.service';
import type { IEstimateRepository } from '../../modules/estimates/repositories/estimate.repository';
import type { EstimateService } from '../../modules/estimates/services/estimate.service';
import type { IInvoiceRepository } from '../../modules/invoices/repositories/invoice.repository';
import type { InvoiceService } from '../../modules/invoices/services/invoice.service';
import type { IPaymentRepository } from '../../modules/payments/repositories/payment.repository';
import type { PaymentService } from '../../modules/payments/services/payment.service';
import type { ISparePartRepository } from '../../modules/inventory/repositories/spare-part.repository';
import type { SparePartService } from '../../modules/inventory/services/spare-part.service';
import type { IInventoryDashboardRepository } from '../../modules/inventory/repositories/inventory-dashboard.repository';
import type { InventoryDashboardService } from '../../modules/inventory/services/inventory-dashboard.service';
import type { IStockAlertRepository } from '../../modules/inventory/repositories/stock-alert.repository';
import type { StockAlertService } from '../../modules/inventory/services/stock-alert.service';
import type { IInventoryAuditRepository } from '../../modules/inventory/repositories/inventory-audit.repository';
import type { InventoryAuditService } from '../../modules/inventory/services/inventory-audit.service';
import type { IInventoryTransferRepository } from '../../modules/inventory/repositories/inventory-transfer.repository';
import type { InventoryTransferService } from '../../modules/inventory/services/inventory-transfer.service';
import type { ISupplierRepository } from '../../modules/suppliers/repositories/supplier.repository';
import type { SupplierService } from '../../modules/suppliers/services/supplier.service';
import type { IPurchaseRepository } from '../../modules/procurement/repositories/purchase.repository';
import type { PurchaseService } from '../../modules/procurement/services/purchase.service';
import type { IDeliveryRepository } from '../../modules/procurement/repositories/delivery.repository';
import type { DeliveryService } from '../../modules/procurement/services/delivery.service';
import type { IReorderSettingRepository } from '../../modules/procurement/repositories/reorder-setting.repository';
import type { ReorderSettingService } from '../../modules/procurement/services/reorder-setting.service';
import type { IPricingHistoryRepository } from '../../modules/procurement/repositories/pricing-history.repository';
import type { PricingHistoryService } from '../../modules/procurement/services/pricing-history.service';
import type { ICrmRepository } from '../../modules/crm/repositories/crm.repository';
import type { CrmService } from '../../modules/crm/services/crm.service';
import type { IInsuranceRepository } from '../../modules/insurance/repositories/insurance.repository';
import type { InsuranceService } from '../../modules/insurance/services/insurance.service';
import type { IFleetRepository } from '../../modules/fleet/repositories/fleet.repository';
import type { FleetService } from '../../modules/fleet/services/fleet.service';
import type { IMarketplaceRepository } from '../../modules/marketplace/repositories/marketplace.repository';
import type { MarketplaceService } from '../../modules/marketplace/services/marketplace.service';
import type { IMarketplaceWritesRepository } from '../../modules/marketplace/repositories/marketplace-writes.repository';
import type { MarketplaceWritesService } from '../../modules/marketplace/services/marketplace-writes.service';
import type { IProviderRepository } from '../../modules/provider/repositories/provider.repository';
import type { ProviderService } from '../../modules/provider/services/provider.service';
import type { IAdministrationRepository } from '../../modules/administration/repositories/administration.repository';
import type { AdministrationService } from '../../modules/administration/services/administration.service';
import type { ILicensingRepository } from '../../modules/licensing/repositories/licensing.repository';
import type { LicensingService } from '../../modules/licensing/services/licensing.service';
import type { IQuotaRepository } from '../../modules/quota/repositories/quota.repository';
import type { QuotaService } from '../../modules/quota/services/quota.service';
import type { CallCenterRepository } from '../../modules/call-center/repositories/call-center.repository';
import type { CallCenterService } from '../../modules/call-center/services/call-center.service';
import type { NotificationsRepository } from '../../modules/notifications/repositories/notifications.repository';
import type { NotificationsService } from '../../modules/notifications/services/notifications.service';
import type { IntegrationsRepository } from '../../modules/integrations/repositories/integrations.repository';
import type { IntegrationsService } from '../../modules/integrations/services/integrations.service';
import type { IotRepository } from '../../modules/iot/repositories/iot.repository';
import type { IotService } from '../../modules/iot/services/iot.service';
import type { DynamicPricingRepository } from '../../modules/dynamic-pricing/repositories/dynamic-pricing.repository';
import type { DynamicPricingService } from '../../modules/dynamic-pricing/services/dynamic-pricing.service';
import type { IFleetManagementRepository } from '../../modules/fleet-management/repositories/fleet-management.repository';
import type { FleetManagementService } from '../../modules/fleet-management/services/fleet-management.service';
import type { IFleetTrackingRepository } from '../../modules/fleet-tracking/repositories/fleet-tracking.repository';
import type { FleetTrackingService } from '../../modules/fleet-tracking/services/fleet-tracking.service';
import type { IHrRepository } from '../../modules/hr/repositories/hr.repository';
import type { HrService } from '../../modules/hr/services/hr.service';
import type { IReportsRepository } from '../../modules/reports/repositories/reports.repository';
import type { ReportsService } from '../../modules/reports/services/reports.service';
import type { IAnalyticsRepository } from '../../modules/analytics/repositories/analytics.repository';
import type { AnalyticsService } from '../../modules/analytics/services/analytics.service';
import type { IAiRepository } from '../../modules/ai/repositories/ai.repository';
import type { AiService } from '../../modules/ai/services/ai.service';
import type { IAiJobEstimationRepository } from '../../modules/ai/repositories/ai-job-estimation.repository';
import type { AiJobEstimationService } from '../../modules/ai/services/ai-job-estimation.service';
import type { IAiMaintenancePredictionRepository } from '../../modules/ai/repositories/ai-maintenance-prediction.repository';
import type { AiMaintenancePredictionService } from '../../modules/ai/services/ai-maintenance-prediction.service';
import type { IAiPartsRecommendationRepository } from '../../modules/ai/repositories/ai-parts-recommendation.repository';
import type { AiPartsRecommendationService } from '../../modules/ai/services/ai-parts-recommendation.service';
import type { IAiScheduleOptimizationRepository } from '../../modules/ai/repositories/ai-schedule-optimization.repository';
import type { AiScheduleOptimizationService } from '../../modules/ai/services/ai-schedule-optimization.service';
import type { IAiChatRepository } from '../../modules/ai/repositories/ai-chat.repository';
import type { AiChatService } from '../../modules/ai/services/ai-chat.service';
import type { IAiOcrDocumentRepository } from '../../modules/ai/repositories/ai-ocr-document.repository';
import type { AiOcrDocumentService } from '../../modules/ai/services/ai-ocr-document.service';
import type { IFeatureFlagRepository } from '../../modules/platform/repositories/feature-flag.repository';
import type { FeatureFlagService } from '../../modules/platform/services/feature-flag.service';
import type { IBackupRepository } from '../../modules/platform/repositories/backup.repository';
import type { BackupService } from '../../modules/platform/services/backup.service';
import type { ISubscriptionRepository } from '../../modules/subscriptions/repositories/subscription.repository';
import type { SubscriptionService } from '../../modules/subscriptions/services/subscription.service';

export const EVENT_BUS = token<EventBus>('EventBus');
export const CUSTOMER_REPOSITORY = token<ICustomerRepository>('CustomerRepository');
export const CUSTOMER_SERVICE = token<CustomerService>('CustomerService');
export const VEHICLE_REPOSITORY = token<IVehicleRepository>('VehicleRepository');
export const VEHICLE_SERVICE = token<VehicleService>('VehicleService');
export const APPOINTMENT_REPOSITORY = token<IAppointmentRepository>('AppointmentRepository');
export const APPOINTMENT_SERVICE = token<AppointmentService>('AppointmentService');
export const GARAGE_REPOSITORY = token<IGarageRepository>('GarageRepository');
export const GARAGE_SERVICE = token<GarageService>('GarageService');
export const JOBCARD_REPOSITORY = token<IJobCardRepository>('JobCardRepository');
export const JOBCARD_SERVICE = token<JobCardService>('JobCardService');
export const ESTIMATE_REPOSITORY = token<IEstimateRepository>('EstimateRepository');
export const ESTIMATE_SERVICE = token<EstimateService>('EstimateService');
export const INVOICE_REPOSITORY = token<IInvoiceRepository>('InvoiceRepository');
export const INVOICE_SERVICE = token<InvoiceService>('InvoiceService');
export const PAYMENT_REPOSITORY = token<IPaymentRepository>('PaymentRepository');
export const PAYMENT_SERVICE = token<PaymentService>('PaymentService');
export const SPARE_PART_REPOSITORY = token<ISparePartRepository>('SparePartRepository');
export const SPARE_PART_SERVICE = token<SparePartService>('SparePartService');
export const INVENTORY_DASHBOARD_REPOSITORY = token<IInventoryDashboardRepository>(
  'InventoryDashboardRepository',
);
export const INVENTORY_DASHBOARD_SERVICE = token<InventoryDashboardService>(
  'InventoryDashboardService',
);
export const STOCK_ALERT_REPOSITORY = token<IStockAlertRepository>('StockAlertRepository');
export const STOCK_ALERT_SERVICE = token<StockAlertService>('StockAlertService');
export const INVENTORY_AUDIT_REPOSITORY = token<IInventoryAuditRepository>('InventoryAuditRepository');
export const INVENTORY_AUDIT_SERVICE = token<InventoryAuditService>('InventoryAuditService');
export const INVENTORY_TRANSFER_REPOSITORY = token<IInventoryTransferRepository>(
  'InventoryTransferRepository',
);
export const INVENTORY_TRANSFER_SERVICE = token<InventoryTransferService>('InventoryTransferService');
export const SUPPLIER_REPOSITORY = token<ISupplierRepository>('SupplierRepository');
export const SUPPLIER_SERVICE = token<SupplierService>('SupplierService');
export const PURCHASE_REPOSITORY = token<IPurchaseRepository>('PurchaseRepository');
export const PURCHASE_SERVICE = token<PurchaseService>('PurchaseService');
export const DELIVERY_REPOSITORY = token<IDeliveryRepository>('DeliveryRepository');
export const DELIVERY_SERVICE = token<DeliveryService>('DeliveryService');
export const REORDER_SETTING_REPOSITORY = token<IReorderSettingRepository>('ReorderSettingRepository');
export const REORDER_SETTING_SERVICE = token<ReorderSettingService>('ReorderSettingService');
export const PRICING_HISTORY_REPOSITORY = token<IPricingHistoryRepository>('PricingHistoryRepository');
export const PRICING_HISTORY_SERVICE = token<PricingHistoryService>('PricingHistoryService');
export const CRM_REPOSITORY = token<ICrmRepository>('CrmRepository');
export const CRM_SERVICE = token<CrmService>('CrmService');
export const INSURANCE_REPOSITORY = token<IInsuranceRepository>('InsuranceRepository');
export const INSURANCE_SERVICE = token<InsuranceService>('InsuranceService');
export const FLEET_REPOSITORY = token<IFleetRepository>('FleetRepository');
export const FLEET_SERVICE = token<FleetService>('FleetService');
export const MARKETPLACE_REPOSITORY = token<IMarketplaceRepository>('MarketplaceRepository');
export const MARKETPLACE_SERVICE = token<MarketplaceService>('MarketplaceService');
export const MARKETPLACE_WRITES_REPOSITORY = token<IMarketplaceWritesRepository>('MarketplaceWritesRepository');
export const MARKETPLACE_WRITES_SERVICE = token<MarketplaceWritesService>('MarketplaceWritesService');
export const PROVIDER_REPOSITORY = token<IProviderRepository>('ProviderRepository');
export const PROVIDER_SERVICE = token<ProviderService>('ProviderService');
export const ADMINISTRATION_REPOSITORY = token<IAdministrationRepository>('AdministrationRepository');
export const ADMINISTRATION_SERVICE = token<AdministrationService>('AdministrationService');
export const LICENSING_REPOSITORY = token<ILicensingRepository>('LicensingRepository');
export const LICENSING_SERVICE = token<LicensingService>('LicensingService');
export const QUOTA_REPOSITORY = token<IQuotaRepository>('QuotaRepository');
export const QUOTA_SERVICE = token<QuotaService>('QuotaService');
export const CALL_CENTER_REPOSITORY = token<CallCenterRepository>('CallCenterRepository');
export const CALL_CENTER_SERVICE = token<CallCenterService>('CallCenterService');
export const NOTIFICATIONS_REPOSITORY = token<NotificationsRepository>('NotificationsRepository');
export const NOTIFICATIONS_SERVICE = token<NotificationsService>('NotificationsService');
export const INTEGRATIONS_REPOSITORY = token<IntegrationsRepository>('IntegrationsRepository');
export const INTEGRATIONS_SERVICE = token<IntegrationsService>('IntegrationsService');
export const IOT_REPOSITORY = token<IotRepository>('IotRepository');
export const IOT_SERVICE = token<IotService>('IotService');
export const DYNAMIC_PRICING_REPOSITORY = token<DynamicPricingRepository>('DynamicPricingRepository');
export const DYNAMIC_PRICING_SERVICE = token<DynamicPricingService>('DynamicPricingService');
export const FLEET_MANAGEMENT_REPOSITORY = token<IFleetManagementRepository>('FleetManagementRepository');
export const FLEET_MANAGEMENT_SERVICE = token<FleetManagementService>('FleetManagementService');
export const FLEET_TRACKING_REPOSITORY = token<IFleetTrackingRepository>('FleetTrackingRepository');
export const FLEET_TRACKING_SERVICE = token<FleetTrackingService>('FleetTrackingService');
export const HR_REPOSITORY = token<IHrRepository>('HrRepository');
export const HR_SERVICE = token<HrService>('HrService');
export const REPORTS_REPOSITORY = token<IReportsRepository>('ReportsRepository');
export const REPORTS_SERVICE = token<ReportsService>('ReportsService');
export const ANALYTICS_REPOSITORY = token<IAnalyticsRepository>('AnalyticsRepository');
export const ANALYTICS_SERVICE = token<AnalyticsService>('AnalyticsService');
export const AI_REPOSITORY = token<IAiRepository>('AiRepository');
export const AI_SERVICE = token<AiService>('AiService');
export const AI_JOB_ESTIMATION_REPOSITORY = token<IAiJobEstimationRepository>('AiJobEstimationRepository');
export const AI_JOB_ESTIMATION_SERVICE = token<AiJobEstimationService>('AiJobEstimationService');
export const AI_MAINTENANCE_PREDICTION_REPOSITORY = token<IAiMaintenancePredictionRepository>('AiMaintenancePredictionRepository');
export const AI_MAINTENANCE_PREDICTION_SERVICE = token<AiMaintenancePredictionService>('AiMaintenancePredictionService');
export const AI_PARTS_RECOMMENDATION_REPOSITORY = token<IAiPartsRecommendationRepository>('AiPartsRecommendationRepository');
export const AI_PARTS_RECOMMENDATION_SERVICE = token<AiPartsRecommendationService>('AiPartsRecommendationService');
export const AI_SCHEDULE_OPTIMIZATION_REPOSITORY = token<IAiScheduleOptimizationRepository>('AiScheduleOptimizationRepository');
export const AI_SCHEDULE_OPTIMIZATION_SERVICE = token<AiScheduleOptimizationService>('AiScheduleOptimizationService');
export const AI_CHAT_REPOSITORY = token<IAiChatRepository>('AiChatRepository');
export const AI_CHAT_SERVICE = token<AiChatService>('AiChatService');
export const AI_OCR_DOCUMENT_REPOSITORY = token<IAiOcrDocumentRepository>('AiOcrDocumentRepository');
export const AI_OCR_DOCUMENT_SERVICE = token<AiOcrDocumentService>('AiOcrDocumentService');
export const FEATURE_FLAG_REPOSITORY = token<IFeatureFlagRepository>('FeatureFlagRepository');
export const FEATURE_FLAG_SERVICE = token<FeatureFlagService>('FeatureFlagService');
export const BACKUP_REPOSITORY = token<IBackupRepository>('BackupRepository');
export const BACKUP_SERVICE = token<BackupService>('BackupService');
export const SUBSCRIPTION_REPOSITORY = token<ISubscriptionRepository>('SubscriptionRepository');
export const SUBSCRIPTION_SERVICE = token<SubscriptionService>('SubscriptionService');
