// Vehicle catalogs for makes, models, years, and nationalities

export interface VehicleMake {
  id: string;
  name: string;
  logo: string; // URL or emoji for simple representation
  country: string;
}

export interface VehicleModel {
  id: string;
  makeId: string;
  name: string;
  years?: number[]; // Available years for this model
}

export const vehicleMakes: VehicleMake[] = [
  { id: "toyota", name: "Toyota", logo: "🚗", country: "Japan" },
  { id: "honda", name: "Honda", logo: "🚗", country: "Japan" },
  { id: "nissan", name: "Nissan", logo: "🚗", country: "Japan" },
  { id: "mazda", name: "Mazda", logo: "🚗", country: "Japan" },
  { id: "subaru", name: "Subaru", logo: "🚗", country: "Japan" },
  { id: "mitsubishi", name: "Mitsubishi", logo: "🚗", country: "Japan" },
  { id: "lexus", name: "Lexus", logo: "🚗", country: "Japan" },
  { id: "infiniti", name: "Infiniti", logo: "🚗", country: "Japan" },
  { id: "acura", name: "Acura", logo: "🚗", country: "Japan" },
  { id: "suzuki", name: "Suzuki", logo: "🚗", country: "Japan" },
  { id: "ford", name: "Ford", logo: "🚙", country: "USA" },
  { id: "chevrolet", name: "Chevrolet", logo: "🚙", country: "USA" },
  { id: "gmc", name: "GMC", logo: "🚙", country: "USA" },
  { id: "dodge", name: "Dodge", logo: "🚙", country: "USA" },
  { id: "jeep", name: "Jeep", logo: "🚙", country: "USA" },
  { id: "chrysler", name: "Chrysler", logo: "🚙", country: "USA" },
  { id: "ram", name: "RAM", logo: "🚙", country: "USA" },
  { id: "cadillac", name: "Cadillac", logo: "🚙", country: "USA" },
  { id: "lincoln", name: "Lincoln", logo: "🚙", country: "USA" },
  { id: "buick", name: "Buick", logo: "🚙", country: "USA" },
  { id: "tesla", name: "Tesla", logo: "⚡", country: "USA" },
  { id: "bmw", name: "BMW", logo: "🏎️", country: "Germany" },
  { id: "mercedes", name: "Mercedes-Benz", logo: "🏎️", country: "Germany" },
  { id: "audi", name: "Audi", logo: "🏎️", country: "Germany" },
  { id: "volkswagen", name: "Volkswagen", logo: "🏎️", country: "Germany" },
  { id: "porsche", name: "Porsche", logo: "🏎️", country: "Germany" },
  { id: "opel", name: "Opel", logo: "🏎️", country: "Germany" },
  { id: "mini", name: "MINI", logo: "🏎️", country: "Germany" },
  { id: "hyundai", name: "Hyundai", logo: "🚗", country: "South Korea" },
  { id: "kia", name: "Kia", logo: "🚗", country: "South Korea" },
  { id: "genesis", name: "Genesis", logo: "🚗", country: "South Korea" },
  { id: "landrover", name: "Land Rover", logo: "🚙", country: "UK" },
  { id: "jaguar", name: "Jaguar", logo: "🏎️", country: "UK" },
  { id: "rollsroyce", name: "Rolls-Royce", logo: "🏎️", country: "UK" },
  { id: "bentley", name: "Bentley", logo: "🏎️", country: "UK" },
  { id: "astonmartin", name: "Aston Martin", logo: "🏎️", country: "UK" },
  { id: "mclaren", name: "McLaren", logo: "🏎️", country: "UK" },
  { id: "ferrari", name: "Ferrari", logo: "🏎️", country: "Italy" },
  { id: "lamborghini", name: "Lamborghini", logo: "🏎️", country: "Italy" },
  { id: "maserati", name: "Maserati", logo: "🏎️", country: "Italy" },
  { id: "alfaromeo", name: "Alfa Romeo", logo: "🏎️", country: "Italy" },
  { id: "fiat", name: "Fiat", logo: "🚗", country: "Italy" },
  { id: "volvo", name: "Volvo", logo: "🚗", country: "Sweden" },
  { id: "saab", name: "Saab", logo: "🚗", country: "Sweden" },
  { id: "peugeot", name: "Peugeot", logo: "🚗", country: "France" },
  { id: "renault", name: "Renault", logo: "🚗", country: "France" },
  { id: "citroen", name: "Citroën", logo: "🚗", country: "France" },
  { id: "bugatti", name: "Bugatti", logo: "🏎️", country: "France" },
  { id: "geely", name: "Geely", logo: "🚗", country: "China" },
  { id: "byd", name: "BYD", logo: "⚡", country: "China" },
  { id: "chery", name: "Chery", logo: "🚗", country: "China" },
  { id: "greatwall", name: "Great Wall", logo: "🚗", country: "China" },
  { id: "haval", name: "Haval", logo: "🚗", country: "China" },
  { id: "nio", name: "NIO", logo: "⚡", country: "China" },
  { id: "xpeng", name: "XPeng", logo: "⚡", country: "China" },
  { id: "other", name: "Other", logo: "🚗", country: "Other" },
];

export const vehicleModels: VehicleModel[] = [
  // Toyota
  { id: "camry", makeId: "toyota", name: "Camry" },
  { id: "corolla", makeId: "toyota", name: "Corolla" },
  { id: "rav4", makeId: "toyota", name: "RAV4" },
  { id: "highlander", makeId: "toyota", name: "Highlander" },
  { id: "tacoma", makeId: "toyota", name: "Tacoma" },
  { id: "tundra", makeId: "toyota", name: "Tundra" },
  { id: "prius", makeId: "toyota", name: "Prius" },
  { id: "4runner", makeId: "toyota", name: "4Runner" },
  { id: "sienna", makeId: "toyota", name: "Sienna" },
  { id: "avalon", makeId: "toyota", name: "Avalon" },
  { id: "supra", makeId: "toyota", name: "Supra" },
  { id: "landcruiser", makeId: "toyota", name: "Land Cruiser" },
  { id: "fortuner", makeId: "toyota", name: "Fortuner" },
  { id: "hilux", makeId: "toyota", name: "Hilux" },
  { id: "yaris", makeId: "toyota", name: "Yaris" },
  // Honda
  { id: "civic", makeId: "honda", name: "Civic" },
  { id: "accord", makeId: "honda", name: "Accord" },
  { id: "crv", makeId: "honda", name: "CR-V" },
  { id: "pilot", makeId: "honda", name: "Pilot" },
  { id: "odyssey", makeId: "honda", name: "Odyssey" },
  { id: "hrv", makeId: "honda", name: "HR-V" },
  { id: "ridgeline", makeId: "honda", name: "Ridgeline" },
  { id: "passport", makeId: "honda", name: "Passport" },
  { id: "fit", makeId: "honda", name: "Fit" },
  { id: "insight", makeId: "honda", name: "Insight" },
  // Nissan
  { id: "altima", makeId: "nissan", name: "Altima" },
  { id: "maxima", makeId: "nissan", name: "Maxima" },
  { id: "sentra", makeId: "nissan", name: "Sentra" },
  { id: "rogue", makeId: "nissan", name: "Rogue" },
  { id: "pathfinder", makeId: "nissan", name: "Pathfinder" },
  { id: "murano", makeId: "nissan", name: "Murano" },
  { id: "frontier", makeId: "nissan", name: "Frontier" },
  { id: "titan", makeId: "nissan", name: "Titan" },
  { id: "kicks", makeId: "nissan", name: "Kicks" },
  { id: "patrol", makeId: "nissan", name: "Patrol" },
  { id: "gtr", makeId: "nissan", name: "GT-R" },
  { id: "370z", makeId: "nissan", name: "370Z" },
  // BMW
  { id: "3series", makeId: "bmw", name: "3 Series" },
  { id: "5series", makeId: "bmw", name: "5 Series" },
  { id: "7series", makeId: "bmw", name: "7 Series" },
  { id: "x1", makeId: "bmw", name: "X1" },
  { id: "x3", makeId: "bmw", name: "X3" },
  { id: "x5", makeId: "bmw", name: "X5" },
  { id: "x6", makeId: "bmw", name: "X6" },
  { id: "x7", makeId: "bmw", name: "X7" },
  { id: "m3", makeId: "bmw", name: "M3" },
  { id: "m5", makeId: "bmw", name: "M5" },
  { id: "i4", makeId: "bmw", name: "i4" },
  { id: "ix", makeId: "bmw", name: "iX" },
  // Mercedes-Benz
  { id: "cclass", makeId: "mercedes", name: "C-Class" },
  { id: "eclass", makeId: "mercedes", name: "E-Class" },
  { id: "sclass", makeId: "mercedes", name: "S-Class" },
  { id: "aclass", makeId: "mercedes", name: "A-Class" },
  { id: "gla", makeId: "mercedes", name: "GLA" },
  { id: "glb", makeId: "mercedes", name: "GLB" },
  { id: "glc", makeId: "mercedes", name: "GLC" },
  { id: "gle", makeId: "mercedes", name: "GLE" },
  { id: "gls", makeId: "mercedes", name: "GLS" },
  { id: "gclass", makeId: "mercedes", name: "G-Class" },
  { id: "amggt", makeId: "mercedes", name: "AMG GT" },
  { id: "eqs", makeId: "mercedes", name: "EQS" },
  // Audi
  { id: "a3", makeId: "audi", name: "A3" },
  { id: "a4", makeId: "audi", name: "A4" },
  { id: "a6", makeId: "audi", name: "A6" },
  { id: "a8", makeId: "audi", name: "A8" },
  { id: "q3", makeId: "audi", name: "Q3" },
  { id: "q5", makeId: "audi", name: "Q5" },
  { id: "q7", makeId: "audi", name: "Q7" },
  { id: "q8", makeId: "audi", name: "Q8" },
  { id: "etron", makeId: "audi", name: "e-tron" },
  { id: "rs6", makeId: "audi", name: "RS6" },
  { id: "r8", makeId: "audi", name: "R8" },
  // Hyundai
  { id: "elantra", makeId: "hyundai", name: "Elantra" },
  { id: "sonata", makeId: "hyundai", name: "Sonata" },
  { id: "tucson", makeId: "hyundai", name: "Tucson" },
  { id: "santafe", makeId: "hyundai", name: "Santa Fe" },
  { id: "palisade", makeId: "hyundai", name: "Palisade" },
  { id: "kona", makeId: "hyundai", name: "Kona" },
  { id: "ioniq5", makeId: "hyundai", name: "IONIQ 5" },
  { id: "ioniq6", makeId: "hyundai", name: "IONIQ 6" },
  { id: "accent", makeId: "hyundai", name: "Accent" },
  // Kia
  { id: "forte", makeId: "kia", name: "Forte" },
  { id: "k5", makeId: "kia", name: "K5" },
  { id: "stinger", makeId: "kia", name: "Stinger" },
  { id: "sportage", makeId: "kia", name: "Sportage" },
  { id: "sorento", makeId: "kia", name: "Sorento" },
  { id: "telluride", makeId: "kia", name: "Telluride" },
  { id: "seltos", makeId: "kia", name: "Seltos" },
  { id: "ev6", makeId: "kia", name: "EV6" },
  { id: "carnival", makeId: "kia", name: "Carnival" },
  // Ford
  { id: "f150", makeId: "ford", name: "F-150" },
  { id: "f250", makeId: "ford", name: "F-250" },
  { id: "mustang", makeId: "ford", name: "Mustang" },
  { id: "explorer", makeId: "ford", name: "Explorer" },
  { id: "escape", makeId: "ford", name: "Escape" },
  { id: "expedition", makeId: "ford", name: "Expedition" },
  { id: "ranger", makeId: "ford", name: "Ranger" },
  { id: "bronco", makeId: "ford", name: "Bronco" },
  { id: "edge", makeId: "ford", name: "Edge" },
  { id: "fusion", makeId: "ford", name: "Fusion" },
  { id: "macheE", makeId: "ford", name: "Mustang Mach-E" },
  // Chevrolet
  { id: "silverado", makeId: "chevrolet", name: "Silverado" },
  { id: "tahoe", makeId: "chevrolet", name: "Tahoe" },
  { id: "suburban", makeId: "chevrolet", name: "Suburban" },
  { id: "equinox", makeId: "chevrolet", name: "Equinox" },
  { id: "traverse", makeId: "chevrolet", name: "Traverse" },
  { id: "blazer", makeId: "chevrolet", name: "Blazer" },
  { id: "colorado", makeId: "chevrolet", name: "Colorado" },
  { id: "camaro", makeId: "chevrolet", name: "Camaro" },
  { id: "corvette", makeId: "chevrolet", name: "Corvette" },
  { id: "malibu", makeId: "chevrolet", name: "Malibu" },
  // Jeep
  { id: "wrangler", makeId: "jeep", name: "Wrangler" },
  { id: "grandcherokee", makeId: "jeep", name: "Grand Cherokee" },
  { id: "cherokee", makeId: "jeep", name: "Cherokee" },
  { id: "compass", makeId: "jeep", name: "Compass" },
  { id: "gladiator", makeId: "jeep", name: "Gladiator" },
  { id: "renegade", makeId: "jeep", name: "Renegade" },
  // Tesla
  { id: "model3", makeId: "tesla", name: "Model 3" },
  { id: "modely", makeId: "tesla", name: "Model Y" },
  { id: "models", makeId: "tesla", name: "Model S" },
  { id: "modelx", makeId: "tesla", name: "Model X" },
  { id: "cybertruck", makeId: "tesla", name: "Cybertruck" },
  // Lexus
  { id: "es", makeId: "lexus", name: "ES" },
  { id: "is", makeId: "lexus", name: "IS" },
  { id: "ls", makeId: "lexus", name: "LS" },
  { id: "rx", makeId: "lexus", name: "RX" },
  { id: "nx", makeId: "lexus", name: "NX" },
  { id: "gx", makeId: "lexus", name: "GX" },
  { id: "lx", makeId: "lexus", name: "LX" },
  { id: "ux", makeId: "lexus", name: "UX" },
  // Land Rover
  { id: "rangerover", makeId: "landrover", name: "Range Rover" },
  { id: "rangeroversport", makeId: "landrover", name: "Range Rover Sport" },
  { id: "rangerovervelar", makeId: "landrover", name: "Range Rover Velar" },
  { id: "rangeroverevoque", makeId: "landrover", name: "Range Rover Evoque" },
  { id: "defender", makeId: "landrover", name: "Defender" },
  { id: "discovery", makeId: "landrover", name: "Discovery" },
  // Porsche
  { id: "911", makeId: "porsche", name: "911" },
  { id: "cayenne", makeId: "porsche", name: "Cayenne" },
  { id: "macan", makeId: "porsche", name: "Macan" },
  { id: "panamera", makeId: "porsche", name: "Panamera" },
  { id: "taycan", makeId: "porsche", name: "Taycan" },
  { id: "boxster", makeId: "porsche", name: "718 Boxster" },
  { id: "cayman", makeId: "porsche", name: "718 Cayman" },
  // Volkswagen
  { id: "golf", makeId: "volkswagen", name: "Golf" },
  { id: "jetta", makeId: "volkswagen", name: "Jetta" },
  { id: "passat", makeId: "volkswagen", name: "Passat" },
  { id: "tiguan", makeId: "volkswagen", name: "Tiguan" },
  { id: "atlas", makeId: "volkswagen", name: "Atlas" },
  { id: "id4", makeId: "volkswagen", name: "ID.4" },
  { id: "arteon", makeId: "volkswagen", name: "Arteon" },
  // Volvo
  { id: "xc40", makeId: "volvo", name: "XC40" },
  { id: "xc60", makeId: "volvo", name: "XC60" },
  { id: "xc90", makeId: "volvo", name: "XC90" },
  { id: "s60", makeId: "volvo", name: "S60" },
  { id: "s90", makeId: "volvo", name: "S90" },
  { id: "v60", makeId: "volvo", name: "V60" },
  { id: "v90", makeId: "volvo", name: "V90" },
  // Mazda
  { id: "mazda3", makeId: "mazda", name: "Mazda3" },
  { id: "mazda6", makeId: "mazda", name: "Mazda6" },
  { id: "cx30", makeId: "mazda", name: "CX-30" },
  { id: "cx5", makeId: "mazda", name: "CX-5" },
  { id: "cx50", makeId: "mazda", name: "CX-50" },
  { id: "cx9", makeId: "mazda", name: "CX-9" },
  { id: "mx5", makeId: "mazda", name: "MX-5 Miata" },
  // Subaru
  { id: "outback", makeId: "subaru", name: "Outback" },
  { id: "forester", makeId: "subaru", name: "Forester" },
  { id: "crosstrek", makeId: "subaru", name: "Crosstrek" },
  { id: "impreza", makeId: "subaru", name: "Impreza" },
  { id: "wrx", makeId: "subaru", name: "WRX" },
  { id: "legacy", makeId: "subaru", name: "Legacy" },
  { id: "ascent", makeId: "subaru", name: "Ascent" },
  // Dodge
  { id: "charger", makeId: "dodge", name: "Charger" },
  { id: "challenger", makeId: "dodge", name: "Challenger" },
  { id: "durango", makeId: "dodge", name: "Durango" },
  { id: "hornet", makeId: "dodge", name: "Hornet" },
  // GMC
  { id: "sierra", makeId: "gmc", name: "Sierra" },
  { id: "yukon", makeId: "gmc", name: "Yukon" },
  { id: "acadia", makeId: "gmc", name: "Acadia" },
  { id: "terrain", makeId: "gmc", name: "Terrain" },
  { id: "canyon", makeId: "gmc", name: "Canyon" },
  { id: "hummer", makeId: "gmc", name: "Hummer EV" },
  // RAM
  { id: "ram1500", makeId: "ram", name: "1500" },
  { id: "ram2500", makeId: "ram", name: "2500" },
  { id: "ram3500", makeId: "ram", name: "3500" },
  // Genesis
  { id: "g70", makeId: "genesis", name: "G70" },
  { id: "g80", makeId: "genesis", name: "G80" },
  { id: "g90", makeId: "genesis", name: "G90" },
  { id: "gv70", makeId: "genesis", name: "GV70" },
  { id: "gv80", makeId: "genesis", name: "GV80" },
  // Ferrari
  { id: "488", makeId: "ferrari", name: "488" },
  { id: "f8", makeId: "ferrari", name: "F8 Tributo" },
  { id: "sf90", makeId: "ferrari", name: "SF90 Stradale" },
  { id: "roma", makeId: "ferrari", name: "Roma" },
  { id: "portofino", makeId: "ferrari", name: "Portofino" },
  { id: "812", makeId: "ferrari", name: "812 Superfast" },
  // Lamborghini
  { id: "huracan", makeId: "lamborghini", name: "Huracán" },
  { id: "urus", makeId: "lamborghini", name: "Urus" },
  { id: "aventador", makeId: "lamborghini", name: "Aventador" },
  { id: "revuelto", makeId: "lamborghini", name: "Revuelto" },
  // Infiniti
  { id: "q50", makeId: "infiniti", name: "Q50" },
  { id: "q60", makeId: "infiniti", name: "Q60" },
  { id: "qx50", makeId: "infiniti", name: "QX50" },
  { id: "qx55", makeId: "infiniti", name: "QX55" },
  { id: "qx60", makeId: "infiniti", name: "QX60" },
  { id: "qx80", makeId: "infiniti", name: "QX80" },
  // Acura
  { id: "tlx", makeId: "acura", name: "TLX" },
  { id: "integra", makeId: "acura", name: "Integra" },
  { id: "rdx", makeId: "acura", name: "RDX" },
  { id: "mdx", makeId: "acura", name: "MDX" },
  { id: "nsx", makeId: "acura", name: "NSX" },
  // Cadillac
  { id: "ct4", makeId: "cadillac", name: "CT4" },
  { id: "ct5", makeId: "cadillac", name: "CT5" },
  { id: "escalade", makeId: "cadillac", name: "Escalade" },
  { id: "xt4", makeId: "cadillac", name: "XT4" },
  { id: "xt5", makeId: "cadillac", name: "XT5" },
  { id: "xt6", makeId: "cadillac", name: "XT6" },
  { id: "lyriq", makeId: "cadillac", name: "LYRIQ" },
  // Lincoln
  { id: "navigator", makeId: "lincoln", name: "Navigator" },
  { id: "aviator", makeId: "lincoln", name: "Aviator" },
  { id: "nautilus", makeId: "lincoln", name: "Nautilus" },
  { id: "corsair", makeId: "lincoln", name: "Corsair" },
  // Jaguar
  { id: "fpace", makeId: "jaguar", name: "F-PACE" },
  { id: "epace", makeId: "jaguar", name: "E-PACE" },
  { id: "ipace", makeId: "jaguar", name: "I-PACE" },
  { id: "ftype", makeId: "jaguar", name: "F-TYPE" },
  { id: "xe", makeId: "jaguar", name: "XE" },
  { id: "xf", makeId: "jaguar", name: "XF" },
  // Maserati
  { id: "ghibli", makeId: "maserati", name: "Ghibli" },
  { id: "quattroporte", makeId: "maserati", name: "Quattroporte" },
  { id: "levante", makeId: "maserati", name: "Levante" },
  { id: "grecale", makeId: "maserati", name: "Grecale" },
  { id: "mc20", makeId: "maserati", name: "MC20" },
  // BYD
  { id: "seal", makeId: "byd", name: "Seal" },
  { id: "dolphin", makeId: "byd", name: "Dolphin" },
  { id: "atto3", makeId: "byd", name: "Atto 3" },
  { id: "han", makeId: "byd", name: "Han" },
  { id: "tang", makeId: "byd", name: "Tang" },
  // Other (generic)
  { id: "other", makeId: "other", name: "Other Model" },
];

// Generate years from 1980 to 2026
export const vehicleYears: number[] = Array.from(
  { length: 2026 - 1980 + 1 },
  (_, i) => 2026 - i
);

export const nationalities = [
  { id: "SA", name: "Saudi Arabia", nameAr: "المملكة العربية السعودية" },
  { id: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة" },
  { id: "KW", name: "Kuwait", nameAr: "الكويت" },
  { id: "QA", name: "Qatar", nameAr: "قطر" },
  { id: "BH", name: "Bahrain", nameAr: "البحرين" },
  { id: "OM", name: "Oman", nameAr: "عُمان" },
  { id: "JO", name: "Jordan", nameAr: "الأردن" },
  { id: "LB", name: "Lebanon", nameAr: "لبنان" },
  { id: "SY", name: "Syria", nameAr: "سوريا" },
  { id: "IQ", name: "Iraq", nameAr: "العراق" },
  { id: "EG", name: "Egypt", nameAr: "مصر" },
  { id: "LY", name: "Libya", nameAr: "ليبيا" },
  { id: "TN", name: "Tunisia", nameAr: "تونس" },
  { id: "DZ", name: "Algeria", nameAr: "الجزائر" },
  { id: "MA", name: "Morocco", nameAr: "المغرب" },
  { id: "SD", name: "Sudan", nameAr: "السودان" },
  { id: "YE", name: "Yemen", nameAr: "اليمن" },
  { id: "PS", name: "Palestine", nameAr: "فلسطين" },
  { id: "IN", name: "India", nameAr: "الهند" },
  { id: "PK", name: "Pakistan", nameAr: "باكستان" },
  { id: "BD", name: "Bangladesh", nameAr: "بنغلاديش" },
  { id: "PH", name: "Philippines", nameAr: "الفلبين" },
  { id: "ID", name: "Indonesia", nameAr: "إندونيسيا" },
  { id: "NP", name: "Nepal", nameAr: "نيبال" },
  { id: "LK", name: "Sri Lanka", nameAr: "سريلانكا" },
  { id: "AF", name: "Afghanistan", nameAr: "أفغانستان" },
  { id: "IR", name: "Iran", nameAr: "إيران" },
  { id: "TR", name: "Turkey", nameAr: "تركيا" },
  { id: "US", name: "United States", nameAr: "الولايات المتحدة" },
  { id: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة" },
  { id: "CA", name: "Canada", nameAr: "كندا" },
  { id: "AU", name: "Australia", nameAr: "أستراليا" },
  { id: "DE", name: "Germany", nameAr: "ألمانيا" },
  { id: "FR", name: "France", nameAr: "فرنسا" },
  { id: "IT", name: "Italy", nameAr: "إيطاليا" },
  { id: "ES", name: "Spain", nameAr: "إسبانيا" },
  { id: "NL", name: "Netherlands", nameAr: "هولندا" },
  { id: "BE", name: "Belgium", nameAr: "بلجيكا" },
  { id: "CH", name: "Switzerland", nameAr: "سويسرا" },
  { id: "AT", name: "Austria", nameAr: "النمسا" },
  { id: "SE", name: "Sweden", nameAr: "السويد" },
  { id: "NO", name: "Norway", nameAr: "النرويج" },
  { id: "DK", name: "Denmark", nameAr: "الدنمارك" },
  { id: "FI", name: "Finland", nameAr: "فنلندا" },
  { id: "PL", name: "Poland", nameAr: "بولندا" },
  { id: "RU", name: "Russia", nameAr: "روسيا" },
  { id: "JP", name: "Japan", nameAr: "اليابان" },
  { id: "CN", name: "China", nameAr: "الصين" },
  { id: "KR", name: "South Korea", nameAr: "كوريا الجنوبية" },
  { id: "SG", name: "Singapore", nameAr: "سنغافورة" },
  { id: "MY", name: "Malaysia", nameAr: "ماليزيا" },
  { id: "TH", name: "Thailand", nameAr: "تايلاند" },
  { id: "VN", name: "Vietnam", nameAr: "فيتنام" },
  { id: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا" },
  { id: "NG", name: "Nigeria", nameAr: "نيجيريا" },
  { id: "KE", name: "Kenya", nameAr: "كينيا" },
  { id: "ET", name: "Ethiopia", nameAr: "إثيوبيا" },
  { id: "BR", name: "Brazil", nameAr: "البرازيل" },
  { id: "MX", name: "Mexico", nameAr: "المكسيك" },
  { id: "AR", name: "Argentina", nameAr: "الأرجنتين" },
  { id: "CO", name: "Colombia", nameAr: "كولومبيا" },
  { id: "OTHER", name: "Other", nameAr: "أخرى" },
];

export const engineTypes = [
  { id: "gasoline", name: "Gasoline", nameAr: "بنزين" },
  { id: "diesel", name: "Diesel", nameAr: "ديزل" },
  { id: "electric", name: "Electric", nameAr: "كهربائي" },
  { id: "hybrid", name: "Hybrid", nameAr: "هجين" },
  { id: "plugin_hybrid", name: "Plug-in Hybrid", nameAr: "هجين قابل للشحن" },
  { id: "hydrogen", name: "Hydrogen", nameAr: "هيدروجين" },
  { id: "natural_gas", name: "Natural Gas", nameAr: "غاز طبيعي" },
];

export const transmissionTypes = [
  { id: "automatic", name: "Automatic", nameAr: "أوتوماتيك" },
  { id: "manual", name: "Manual", nameAr: "يدوي" },
  { id: "cvt", name: "CVT", nameAr: "CVT" },
  { id: "dct", name: "Dual Clutch (DCT)", nameAr: "قابض مزدوج" },
  { id: "amt", name: "Automated Manual (AMT)", nameAr: "يدوي آلي" },
];

export const colors = [
  { id: "white", name: "White", nameAr: "أبيض", hex: "#FFFFFF" },
  { id: "black", name: "Black", nameAr: "أسود", hex: "#000000" },
  { id: "silver", name: "Silver", nameAr: "فضي", hex: "#C0C0C0" },
  { id: "gray", name: "Gray", nameAr: "رمادي", hex: "#808080" },
  { id: "red", name: "Red", nameAr: "أحمر", hex: "#FF0000" },
  { id: "blue", name: "Blue", nameAr: "أزرق", hex: "#0000FF" },
  { id: "green", name: "Green", nameAr: "أخضر", hex: "#008000" },
  { id: "brown", name: "Brown", nameAr: "بني", hex: "#8B4513" },
  { id: "beige", name: "Beige", nameAr: "بيج", hex: "#F5F5DC" },
  { id: "gold", name: "Gold", nameAr: "ذهبي", hex: "#FFD700" },
  { id: "orange", name: "Orange", nameAr: "برتقالي", hex: "#FFA500" },
  { id: "yellow", name: "Yellow", nameAr: "أصفر", hex: "#FFFF00" },
  { id: "purple", name: "Purple", nameAr: "بنفسجي", hex: "#800080" },
  { id: "navy", name: "Navy Blue", nameAr: "كحلي", hex: "#000080" },
  { id: "maroon", name: "Maroon", nameAr: "عنابي", hex: "#800000" },
  { id: "champagne", name: "Champagne", nameAr: "شمباني", hex: "#F7E7CE" },
];

// Helper function to get models for a specific make
export function getModelsForMake(makeId: string): VehicleModel[] {
  return vehicleModels.filter((model) => model.makeId === makeId);
}

// Helper function to get make by ID
export function getMakeById(makeId: string): VehicleMake | undefined {
  return vehicleMakes.find((make) => make.id === makeId);
}

// Helper function to get nationality by ID
export function getNationalityById(id: string) {
  return nationalities.find((n) => n.id === id);
}
